name: firebase_verify_token
description: Plugin to verify a firebase jwt token by a specific project id
version: 0.0.5
author: Enzo De Simone <enzodesimone@besimsoft.com>
homepage: https://github.com/enzo-desimone/firebase_verify_token

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  jose: ^0.3.4
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: