name: firebase_verify_token
description: Plugin to verify a firebase jwt token by a specific project id
version: 0.0.7
homepage: https://github.com/enzo-desimone/firebase_verify_token

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  jose_plus: ^0.4.3
  ntp: ^2.0.0

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter: